# Generated by Django 3.1.7 on 2021-02-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_auto_20210227_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.TextField(choices=[('new', 'Новый'), ('progress', 'В процессе'), ('done', 'Сделано')], max_length=30, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'db_table': 'lists',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
