# Generated by Django 3.1.7 on 2021-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_auto_20210227_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='list',
            name='list',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.TextField(choices=[('new', 'Новый'), ('progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
