# Generated by Django 3.1.7 on 2021-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_auto_20210227_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(default=' ', max_length=200, verbose_name='Поле'),
            preserve_default=False,
        ),
    ]
